//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4952
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHC.OrderWater.Commons.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHC.OrderWater.Commons.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;gb2312&quot; ?&gt;
        ///&lt;HELLO&gt;
        ///
        ///  &lt;!-- 公历节日开始 --&gt;
        ///  &lt;AD&gt;
        ///    &lt;feast day=&quot;0101&quot; name=&quot;元旦&quot; sayhello=&quot;yes&quot;&gt;
        ///      &lt;hello&gt;新年好！祝您在新的一年里身体健康，事业进步！&lt;/hello&gt;
        ///      &lt;!-- 从网站根目录算起 --&gt;
        ///      &lt;img&gt;./img/theme/0101.gif&lt;/img&gt;
        ///    &lt;/feast&gt;
        ///    &lt;feast day=&quot;0202&quot; name=&quot;世界湿地日&quot; sayhello=&quot;no&quot;&gt;
        ///      &lt;img&gt;&lt;/img&gt;
        ///      &lt;hello&gt;&lt;/hello&gt;
        ///    &lt;/feast&gt;
        ///    &lt;feast day=&quot;0210&quot; name=&quot;国际气象节&quot; sayhello=&quot;no&quot;&gt;
        ///      &lt;img&gt;&lt;/img&gt;
        ///      &lt;hello&gt;&lt;/hello&gt;
        ///    &lt;/feast&gt;
        ///    &lt;feast day=&quot;0214&quot; name=&quot;情人节&quot; sayhello=&quot;yes [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CCalendarData {
            get {
                return ResourceManager.GetString("CCalendarData", resourceCulture);
            }
        }
    }
}
